name: dart_suite
description: A set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality.
version: 0.0.2
maintainer: Rahul Sharma (@rahulsharmadev)
homepage: https://github.com/rahulsharmadev0
repository: https://github.com/rahulsharmadev0/suite/tree/main/packages/dart_suite
issue_tracker: https://github.com/rahulsharmadev0/suite/issues
documentation: https://github.com/rahulsharmadev0/suite/blob/main/packages/dart_suite/README.md

environment:
  sdk: ">=3.3.2 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  crypto: ">=3.0.5 <4.0.0"
  collection: ">=1.18.0 <2.0.0"
  meta: ">=1.12.0 <2.0.0"
  intl: ">=0.19.0 <1.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
