name: bloc_suite
version: 0.0.8
description: Bloc Suite is a comprehensive package that extends the functionality of the Flutter Bloc library.
maintainer: Rahul Sharma (@rahulsharmadev)
homepage: https://github.com/rahulsharmadev0
repository: https://github.com/rahulsharmadev0/suite/tree/main/packages/bloc_suite
issue_tracker: https://github.com/rahulsharmadev0/suite/issues
documentation: https://github.com/rahulsharmadev0/suite/blob/main/packages/bloc_suite/README.md
topics: [bloc, concurrency, state-management]

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ">=8.1.4 <9.4.0"
  flutter_bloc: ">=8.1.4 <9.4.0"
  equatable: ">=2.0.0 <3.0.0"
  logger: ">=2.5.0 <3.0.0"
  meta: ">=1.16.0 <2.0.0"
  rxdart: ">=0.27.7 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.25.6

screenshots:
  - description: The bloc_suite package logo.
    path: screenshots/logo.png
