name: gen_suite
description: A powerful code generation package.
version: 0.0.1
repository: https://github.com/rahulsharmadev0/suite
homepage: https://github.com/rahulsharmadev0/suite/tree/main/packages/gen_suite
documentation: https://github.com/rahulsharmadev0/suite/tree/main/packages/gen_suite#readme
issue_tracker: https://github.com/rahulsharmadev0/suite/issues

topics:
  - codegen
  - singleton
  - build-runner
  - source-gen
  - dart

environment:
  sdk: ">=3.3.2 <4.0.0"

# Add regular dependencies here.
dependencies: 
  dart_suite: ^0.0.5
  code_builder: ^4.10.1
  analyzer: ">=7.4.0 <8.0.0"
  build: ^3.0.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.6.0
  build_test: ^3.3.0
  lints: ^6.0.0
  test: ^1.25.6
