name: Publish dart_suite to pub.dev

on: [workflow_dispatch]

env:
  XDG_CONFIG_HOME: ~/.config

jobs:
  publish:
    defaults:
      run:
        working-directory: packages/dart_suite

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.7.0"

      - name: 📦 Install Dependencies
        run: |
          dart pub get

      - name: 🔍 Run Analysis
        run: dart analyze

      - name: 🧪 Run Tests
        run: dart test

      - name: 🔐 Setup Pub Credentials
        if: success() && github.ref == 'refs/heads/main'
        run: |
          mkdir -p "$XDG_CONFIG_HOME/dart"
          echo '${{ secrets.PUB_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
          ls -l "$XDG_CONFIG_HOME/dart"

      - name: 🎯 Verify Package
        if: success()
        run: dart pub publish --dry-run

      - name: 📢 Publish Package
        if: success() && github.ref == 'refs/heads/main'
        run: dart pub publish -f
